# Generated by Django 5.0 on 2023-12-12 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='user',
            new_name='user_id',
        ),
    ]
