# Generated by Django 5.0 on 2023-12-12 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_user_hospitalprofile_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='user_id',
            new_name='user',
        ),
    ]
