# Generated by Django 5.0 on 2024-01-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_hospitalprofile_id_alter_hospitalprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=25)),
                ('tin_number', models.BigIntegerField(blank=True, null=True)),
                ('country', models.CharField(default='Uganda', max_length=25)),
                ('town_or_state', models.CharField(default='Kampala', max_length=25)),
                ('street_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
