# Generated by Django 5.0 on 2024-01-09 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_registeredhospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredhospital',
            name='hospital_name',
            field=models.CharField(max_length=100),
        ),
    ]
