# Generated by Django 5.0 on 2024-01-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_hospitalprofile_role_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='telephone_number',
            new_name='phone_number',
        ),
    ]
