# Generated by Django 5.0 on 2024-03-12 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_rename_telephone_number_hospitalprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='admin_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
