# Generated by Django 5.0 on 2024-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_hospitalprofile_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalprofile',
            name='admin_status',
            field=models.CharField(choices=[('Regular', 'Regular'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
