# Generated by Django 5.0 on 2024-03-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_hospitalprofile_admin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='account_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True),
        ),
    ]
