# Generated by Django 5.0 on 2024-02-03 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('brand', models.CharField(max_length=40)),
                ('formulation', models.CharField(choices=[('Injectable', 'Injectable'), ('Tablets', 'Tablets'), ('Capsules', 'Capsules'), ('Syrup', 'Syrup'), ('Cream', 'Cream'), ('Pessary', 'Pessary'), ('Drops', 'Drops'), ('Lozenge', 'Lozenge')], max_length=20)),
                ('strength_value', models.IntegerField(null=True)),
                ('strength_value_units', models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('ml', 'ml')], max_length=10)),
                ('quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
