# Generated by Django 5.0 on 2024-02-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_rename_medications_medication'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='hospital',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
