# Generated by Django 5.0 on 2023-12-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_patientrecord_test_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='test_for',
            field=models.TextField(null=True),
        ),
    ]
