# Generated by Django 5.0 on 2023-12-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_patientvital'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
