# Generated by Django 5.0 on 2023-12-20 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_patientvital_doctor_patientvital_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='test_for',
            new_name='test_methods',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='test_method',
            new_name='test_results',
        ),
        migrations.RemoveField(
            model_name='patientrecord',
            name='test_result',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='tests_for',
            field=models.TextField(null=True),
        ),
    ]
