# Generated by Django 5.0 on 2023-12-26 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_patientbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='medical_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.patientrecord'),
        ),
    ]
