# Generated by Django 5.0 on 2024-01-04 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_patientbill_medical_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
