# Generated by Django 5.0 on 2024-01-09 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_registeredhospitals'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegisteredHospitals',
            new_name='RegisteredHospital',
        ),
    ]
