# Generated by Django 5.0 on 2024-01-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_registeredhospital_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registeredhospital',
            name='street',
        ),
        migrations.AddField(
            model_name='registeredhospital',
            name='street_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
