# Generated by Django 5.0 on 2024-01-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_registeredhospital_street_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredhospital',
            name='street_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='registeredhospital',
            name='tin_number',
            field=models.BigIntegerField(blank=True),
        ),
    ]
