# Generated by Django 5.0 on 2024-01-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_alter_registeredhospital_tin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredhospital',
            name='tin_number',
            field=models.BigIntegerField(blank=True),
        ),
    ]
