# Generated by Django 5.0 on 2024-01-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_registeredhospital_tin_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeredhospital',
            name='street_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registeredhospital',
            name='tin_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
