# Generated by Django 5.0 on 2024-01-13 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_delete_registeredhospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='test_methods',
            new_name='conclusions',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='tests_for',
            new_name='impressions',
        ),
        migrations.RenameField(
            model_name='patientrecord',
            old_name='prescriptions',
            new_name='management',
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='investigations',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientvital',
            name='oxygen_circulation',
            field=models.IntegerField(null=True),
        ),
    ]
