# Generated by Django 5.0 on 2024-01-20 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_patient_address_patient_next_of_kin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientvital',
            old_name='oxygen_circulation',
            new_name='oxygen_saturation',
        ),
    ]
