# Generated by Django 5.0 on 2024-01-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_rename_oxygen_circulation_patientvital_oxygen_saturation'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='family_history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='gyn_obs_history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='medical_hostory',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='social_history',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='surgical_history',
            field=models.TextField(null=True),
        ),
    ]
