# Generated by Django 5.0 on 2024-01-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_patientrecord_family_history_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientrecord',
            old_name='medical_hostory',
            new_name='medical_history',
        ),
    ]
