# Generated by Django 5.0 on 2024-01-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rename_medical_hostory_patientrecord_medical_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='record_status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
