# Generated by Django 5.0 on 2024-01-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_patientrecord_record_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='test_cost_list',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientbill',
            name='test_list',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
