# Generated by Django 5.0 on 2024-01-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_patientbill_test_cost_list_patientbill_test_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbill',
            name='test_cost_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
