# Generated by Django 5.0 on 2024-01-28 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_patientbill_test_cost_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientbill',
            name='medication_fees_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
