# Generated by Django 5.0 on 2024-01-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_patientbill_medication_fees_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='test_attachments',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
