# Generated by Django 5.0 on 2024-03-15 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_alter_patientbill_doctor_alter_patientvital_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientbill',
            name='medical_record',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.patientrecord'),
        ),
    ]
